# Marketing, Hedging, and Crop Insurance

**Highlights**

-   Purchasing crop insurance provides protection against catastrophic loss in the event of crop failure, and/or significant price decline between planting and harvest
-   How much protection crop insurance alone provides varies based on pre-harvest price movements
-   Crop insurance alone does not provide an optimal marketing plan for some scenarios of price movement planting-harvest

**Check Your Understanding**

-   

## Brief History of Crop Insurance Prior Federal Farm Support Programs

Currently crop insurance dominates the landscape of federally sponsored farm programs for risk management [@walters2017cropinsNI]. However, the history of market interventions and price supports in the United States is long and varied. Understanding the economic and political motivations for moving from price supports and ad hod disaster payments (payments made when there is a large unexpected crop failure) to federally subsidized crop insurance is interesting, However, a full account is beyond the scope of this chapter. Readers can refer to the following for additional historical context [@babcock2005LDP; @glauber2016policy; @cochran1951; @marcus1986; @lichtenberg1986; @Pricesuphis1984].

The short story is that price supports can be distort markets by creating inefficiency in production decisions and generate ill will with trading partners through subsidizing too much production and lowering world prices to the detriment of farmers in other countries. Further, ad hoc disaster payments are by nature not predictable in the timing of when they are needed nor in the size of the need. Both of these created an appetite among lawmakers for a farm support program whose cost was more predictable.

Over the last 30 years crop insurance has come to be the dominant way in which federally sponsored risk management is administered to commodity producers. Two challenges had to be overcome, however.

First, crop insurance is a product that is not possible to be offered exclusively by the private sector. Insurance markets can exist in the private sector when the insured losses are relatively small (compared to premium collected) and predictable from year-to-year [@babcock2006gooddeal]. Crop insurance is neither of these things because 1) losses are typically highly correlated. When there is a crop failure, most farmers in the affected region experience a loss and make a claim on the policy. This makes it very hard for a private insurance company to ensure they have enough liquidity to pay for losses in the event of a widespread crop failure. Therefore, without a federal backstop to the policies, the private market could never offer crop insurance.

Second, when the first crop insurance programs were rolled out in the 1980's and 1990's farmers were not signing up for crop insurance at high enough rates to prevent the need for ad hoc disaster payments. This is a problem because the administration of the federal crop insurance program is costly, so if taxpayers have to pay to administer the crop insurance program and pay for ad hoc disaster from time-to-time, the program is not meeting its purpose and wasting taxpayer money at the same time [@babcock2006gooddeal].

The solution Congress settled on was to increase subsidies for crop insurance premiums to a level where farmers voluntarily purchase enough coverage to reduce the need for frequent disaster payments. Federal subsidies for crop insurance average 62% of the premium cost [@zulauf2016cropins].

## Overview of Typical Crop Insurance offerings

**Yield Protection**

**Revenue Protection**

**Revenue Protection with Harvest Price Exclusion**

**Disclaimer**

## Marketing Strategies Paired with Crop Insurance Protection
