# Cattle Markets and the Livestock Crush

<span style="color:red">Interested in more? Please let me know by</span> [taking the survey](https://forms.gle/Q3VByCQZHjfQSy9D7)! 


This chapter covers the basic production cycle and ownership structures in beef cattle markets. We cover cow-calf, backgrounder, and finisher/feedlot operations. We discuss the basic geography of beef cattle production, and various biological constraints that impact market prices.

In the United States, beef cattle production tends to be segmented between cow-calf operations that keep a breeding herd of cows for the purposes of having calves for sale every year; backgrounder operations that buy 'light' calves and feed them grain until they are big enough to go to a finisher or feedlot operation where the calves are fed a grain-based diet until they are big enough to slaughter. These three stages of the production process are usually managed by independent firms, so that the cow-calf operator is a different entity than the backgrounder, who is a different entity than the finisher. There are cases of more vertically integrated operations, but this is relatively rare.

## The Cow-Calf Operation

In a typical cow-calf operation, the producer maintains a herd of breeding cows that each have one calf per year for sale at market. The cow-calf producer needs to own or lease land for summer pasture, winter pasture, and hay production. Hay is the dried forage fed to cattle in the winter months when grass is usually dormant. Alternatively the producer could purchase hay on the open market, but it is often more cost effective to 'put up' one's own hay.

### Calandar of Production for the Cow-calf Producer

This outline borrows heavily from the [Beef Production Calendar](http://beef.unl.edu/beefprodcal.shtml) published by the Beef Cattle Extension effort of the University of Nebraska Extension system.

Most cow-calf producers operate under a spring calving production system. In this system, calves are born in the months of February, March, and April, and can be weaned and marketed in the fall of the same calendar year.

#### February, March, April

Calves are born during the months of February, March, and April. Males are called bull calves and females are called heifers. Newborn calves weight on average between 50-80lbs. At this time the producer makes decisions about any older cows that need to be culled from the herd and chooses heifer calves to replace culled breeding heifers. During these months the cows and newborn calves are on winter pasture, and usually being fed supplemental forage of hay.

#### May

The cows and calves usually go to summer pasture during the month of May or early June. The exact date depends on when the grass in the summer pasture has grown to a sufficient amount to sustain the herd. Bull calves are castrated before going to summer pasture. Once castrated, male calves are called steers.

#### June, July, August

Bulls are placed with the cow herd to breed. The market for bulls is a totally different pricing model. Since one bull breeds the whole herd of cows, if a producer wants to invest in specific genetic traits, it makes more sense to buy one quality bull, than good genetics for every cow. Some farms specialize in the production of high quality bulls and semen.[^beefcattlemarkets-1]

[^beefcattlemarkets-1]: For example, [Judd Ranch](http://www.juddranch.com/) in Pomona, KS, and [Prairie View Farms](http://www.pvfangus.com/) in Gridley, IL.

Some producers, particularly ones who run a combination cow-calf/commercial grain operation will place [creep feeders](https://www.google.com/search?q=creep+feeder&espv=2&biw=1920&bih=1075&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAmoVChMI18ne2paTyQIVSJUeCh3eMw5X) out with the herd on summer grass. Creep feeders allow smaller calves access to grain to feed at-will, but mature cows are too big to eat the grain.

During the summer months when the cattle out on summer pasture there is little day-to-day care that the herd needs. Typically, during this time the cow-calf producer is busy baling hay to feed the herd during the winter months. Fields of grass are let grow to maximum volume/nutrition, then is cut, dried, and baled for storage until winter.

#### September

Cattle should be bred, so some producers will 'preg check' their cows to determine if any are open (not pregnant). Bulls are pulled from the pastures. Open cows may be culled immediately or kept to attempt to breed in the next cycle.

#### October

In October, the herd will have exhausted the summer forage, so they are brought to winter pastures. Calves are weaned at this time and usually weight 500-600lbs after spending the summer eating grass and mothers milk. Once calves are weaned they can be sold to a backgrounder, or fed for a while on the farm. The operator decides when to sell based on available space to keep the calves on the farm, and the price of grain. If grain prices are cheap enough, the producer can feed the calves and earn more profit, since calves are sold by the pound, the heavier they are, the more total dollars they sell for.

[OSU Fence Line Weaning Video](https://www.youtube.com/watch?v=qpGuOOA-fYU)

[OSU Forage Prospects Video](https://www.youtube.com/watch?v=JyvTl9PVdMQ#action=share)

#### November, December, January

Continue rotating winter pasture and feeding hay for forage.

## The Backgrounder/Stocker

A backgrounder is in the business of buying light calves (weighing approximately 500 lbs) and feeding them grain-based rations until they have gained 100lbs or more. As noted above, the cow-calf producer may decide to background his own calves or an entity strictly in the business of backgrounding may buy light calves at auction or directly from a cow-calf producer.

A backgrounder who purchases calves at auction or from a cow-calf producer must consider weight and gender of the calf.

### Bull or Heifer Calf?

Bull calves put on weight faster than heifer calves, so bull calves bring more money than heifer calves.

### Weight of Calves

Smaller (younger) calves gain weight faster than heavier (older) calves so smaller calves

Examine this USDA Market News report from the [Farmers & Ranchers Livestock Commission Co.](http://www.ams.usda.gov/mnreports/dc_ls143.txt) in Salina, KS.

## The Large Feedlot

Feedlots[^beefcattlemarkets-2] with more than 1,000 head finish more than 80% of fed cattle. So the production of beef starts out with the very distributed cow-calf and backgrounder operations, but the stage of production is highly concentrated at the final stages.

[^beefcattlemarkets-2]: Most of the information in this section is taken from the [Feedlot Finishing Cattle Fact Sheet](http://www.beefusa.org/uDocs/Feedlot%20finishing%20fact%20sheet%20FINAL_4%2026%2006.pdf) published by the Beef Checkoff program.

When calves come to the large feedlots for finishing, they are typically 12-18 months old and range from 700-900lbs when they arrive. The will spend three to six months in the feedlot eating a diet of grain (with corn being the largest component) and hay. Calves gain about 2.5 to 4 pounds per day, converting about 6 lbs of feed into 1 lbs of weight gain.

Large feedlots divide the calves into pens of 100 to 125 animals per pen, so limit the spread of disease. If one pen has an outbreak of some kind of infection, they can be isolated and treated.

The dense concentration of animals in one place requires an active waste management system. All large feedlots have large digester ponds, where waste is dumped so that microorganisms in the ponds can break down the toxins before they leach into the local water supply.

## Beef Packing Plants

The large feedlots sell fattened calves to beef packing plants. Many packing plants are located close to large feedlot operations.

[See some feedlots via satellite](http://maps.google.com)

## Cattle Auctions

Most calves are sold from the cow-calf operation to a backgrounder or feedlot at auction. In beef cattle intensive areas, there will be a livestock auction houses, also called 'sale barns' at least every 30-60 miles. Similar to the coverage grain elevators have in grain intensive areas. Cow-calf producers bring their calves to the auction market the day before the sale and they are kept and cared for in separate pens arranged by ownership. The producer pays the sale barn a commission for selling their calves and fees for the feed, water, and shelter the calves receive from their arrival at the sale barn until the new owner transports them elsewhere.

Both buyers and sellers are often present at the auction. Large feedlots and backgrounders will have agents buying calves in the disperse local markets. Visual inspection in-person in crucial to the buyer because they have an interest to make sure the calves they buy are healthy and not injured. Also, temperament of the calves can be observed, which may be a concern for some operations.

Workers at the sale barn bring the pens of calves through the ring[^beefcattlemarkets-3] and buyers examine the calves on the spot and place bids. The winning bidder pays the auction house and takes the calves to a new location usually the same day.

[^beefcattlemarkets-3]: The ring is the small pen into which the cattle are brought in front of the audience of buyers.

[Cattle Sale Barn - America's Heartland](https://www.youtube.com/watch?v=m0iiTk3MQ3k)

[Cattle Auction](https://www.youtube.com/watch?v=ACKT5jWJHTI)

[Cattle Auctioneer - 2012 Drought](https://www.youtube.com/watch?v=Ig514nyWQho)

## The Cattle Crush 8-4-2

The large feedlot operations are run by commercial firms with the resources and expertise to engage in sophisticated hedging strategies. This has led to the success of two cattle futures contracts: feeder cattle 50,000 lbs of 'light calves', live cattle 40,000 lbs of fed cattle (1,050 - 1,500 per animal). These two cattle contracts, along with corn futures tracks the profitability of finishing cattle and can be used for hedging purposes.

The Feeder Cattle contract is financially settled, which means it is not physically settled. Futures settle to the [CME Feeder Cattle Index](http://www.cmegroup.com/market-data/reports/cash-settled-commodity-index-prices.html), based on cash sales reported to the USDA Ag Market News service in active cash cattle markets.

The Live Cattle contract is physically settled, so the small number of deliveries make the final trades in the futures contract grounded in real prices. Quality is adjusted using the Live Equivalent Choice-Select Spread. Details of a deliverable unit can be found in the [CME Rulebook](http://www.cmegroup.com/rulebook/CME/II/100/101/101.pdf)

### Details of the Spread[\^cattlespread]

One feeder cattle contract covers about 66 animals (50,000 lbs divided by 750 lbs per animal), and one live cattle futures covers about 32 animals (40,000 lbs divided by 1,250 lbs per animal) so the number of live cattle futures used must double the number of feeder cattle contracts used.

Using the rule of thumb that 6 lbs of feed produces 1 lb of gain and beef cattle feed is about 75% corn, it will take 198,000 lbs of feed (148,000 lbs of corn) to grow 66 animals from 750 lbs to 1,250 lbs. This is about 2,651 bushels of corn. Since once futures contract is 5,000 bushels, an 8-4-2 spread is often used: 8 contracts Live Cattle, 4 contracts Feeder Cattle, and 2 contracts Corn futures. This spread hedges approximately 266 animals placed at 750 lbs, marketed at 1,250 lbs, and fed 10,678 bushels of corn.

Since finishing cattle takes three to six months, timing of contract expiration must be considered carefully. In general one should buy feeder cattle contracts that mature 6 months prior to the maturity of live cattle contracts sold, and corn contracts should be sold in between these two dates. For example Sell 8 June live cattle contracts, buy 4 January feeder cattle contracts, and buy 2 March corn contracts. In general, the timing of the contracts should match the timing of transactions in the cash market as closely as possible.

## External Readings

[How Profitable is Backgrounding Cattle?](http://www2.econ.iastate.edu/faculty/lawrence/Acrobat/Backgrounding%20Cattle.pdf)

John Lawrence at Iowa State examines the historical profitability of backgrounding cattle. He considers backgrounding steers versus heifers and lighter calves (450 lbs) versus heavier calves (550 lbs).

## Exercise

Into an Excel spreadsheet, download futures prices for January 2017 Feeder Cattle futures prices ([CME/FCF2017](https://www.quandl.com/data/CME/FCF2017)), March 2017 Corn futures prices ([CME/CH2017](https://www.quandl.com/data/CME/CH2017)), and June 2017 Live Cattle futures prices ([CME/LCM2017](https://www.quandl.com/data/CME/LCM2017)) from Quandl.com.

1.  Suppose you perform risk management for a large feedlot in Western Kansas. You decide on December 1st, 2016 that you will buy 266 feeder cattle on December 20th, 2016 and feed them out to market weight when you will sell them to a packer on May 20, 2017. You need to hedge exposure to the price risk you face in feeding the steers to market weight. Assume you place the animals at 750 lbs and market them at 1250 lbs.

    a.  State the futures trades you will make to put on a cattle crush spread and hedge this price risk. Note the contracts bought/sold, and the dates on which you buy/sell to open and sell/buy to close your futures positions.
    b.  Calculate the gain or loss in your futures position as of May 20, 2015, include changes in the basis in your calculation.
    c.  Calculate the prices paid/recieved in the cash market.
    d.  What was your profit/loss per cwt (hundred weight)?
    e.  Describe how this change in value 'hedges' your price exposure in feeding steers to market weight.
