# Preface {.unnumbered}

[Interested in more? Please let me know by]{style="color:red"} [taking the survey](https://forms.gle/Q3VByCQZHjfQSy9D7)!

This is a book for beginners who want to study commodity price analysis from a fundamental perspective. These chapters are derived from my lecture notes teaching ACE 427: Commodity Price Analysis at the University of Illinois, and then AGEC 421 at Purdue University. The first outline of the book was based an outline given to me by Scott Irwin, who has taught ACE 427 at the University of Illinois for years.

This book is targeted at the upper level undergraduate student, or professional beginning a career related to commodity markets. The objective is to familiarize the reader with the sources of market information and research commonly used by practicing professionals working in the industry.

This book is updated with current information in the tables and figures each time I teach the course. Previous versions of the book can be found [here](https://github.com/mindymallory/PriceAnalysis/releases).

For readers interested in more in-depth analysis of commodity prices using statistical software, I had been working on an [R Companion](http://mindymallory.github.io/R-Companion-Price-Analysis/index.html) to this book, but I have indefinitely paused development of this. If you are interested in the R code to create most of the tables and figures in this book from publicly available sources, you can study the script I use to update this book [here](https://github.com/mindymallory/PriceAnalysis/blob/master/assets/make-assets.Rmd).

To see some videos working through excel-based exercises I have developed for most chapters, see the youtube channel, [here](https://www.youtube.com/@uiucace4277/videos). Note that chapter order may have changed from the older videos to the order in the current form of the book.

# About the Author {.unnumbered}

Mindy L. Mallory is an associate professor and Clearing Corporation Foundation Chair of Food and Agricultural Marketing in the Department of Agricultural Economics at Purdue University.

Dr. Mallory’s research focuses on commodity markets and marketing issues, especially related to commodity futures and options markets. Topics of special interest include forecasting, liquidity costs, and price discovery.

## Contact {.unnumbered}

Mindy L. Mallory\
mlmallor at purdue dot edu\
<https://mindymallory.github.io/>\
<http://mindymallory.com/>

<p>© Mindy L. Mallory 2021</p>
