---
title: "Preface"
output: md_document
---

I am writing *Commodity Price Analysis: Understand and Produce Market Commentary and Forecasts* and *R Companion to Commodity Price Analysis* while teaching ACE 427, an upper level course on Price Analysis at the University of Illinois. The books are intended to be read together, but one could read *Commodity Price Analysis* without reading the *R Companion*. They are written as separate books because I can imagine some will prefer to read the general coverage of *Commodity Price Analysis* and may not be interested in learning R for analysis.

These books are still very early in their development. I am releasing them at such and early stage partly because the Lean Publishing model of 'Publish Early, Publish Often' (with reader feedback) appeals to me. Another concern is purely practical. This will be the assigned text for ACE 427 in Fall 2015 and chapters will be finished only shortly before readings and exercises are assigned. Because the book is in its early development stage, expect typos and other errors in the books. Knowing this, the book will remain available for free, at least through December. During this time updates will be released often to keep up with my course. 

I am eager to hear reader feedback about the structure and scope of the books, and an feed back is appreciated. If you find errors, please alert me via the [Leanpub](http://leanpub.com) website. 

Mindy Mallory