---
title: "Chapters 1, 2, and 3 of Price Analysis"
subtitle: ""
author: ""
institute: ""
date: ""
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: TRUE
---



```{r setup, include=FALSE}
library(xaringanthemer)
options(htmltools.dir.version = FALSE)

purduegold <- '#CEB888'
colorscheme <- purduegold
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  #base_color = purduegold,
  primary_color = colorscheme,
  secondary_color = "black",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```


---

# Please read chapters 1 and 2 on your own

---

# Chapter 3: How to find information

+ Market Commentary
+ Futures Price Quotes
 + Futures Symbols
+ Futures Spreads
+ USDA Reports

---

# Market Commentary

