---
title: "ACE 427 Commodity Price Analysis and Forecasting"
output: slidy_presentation
theme: uulm
---

# Change of Pace Today

- Step back and look more closely at issues in forecasting yields
- Federal Reserve Board's decision on the Fed Funds Rate. 

1. Read and Discuss: [Forming Expectations for the 2015 U.S. Average Corn Yield: What Does History Teach Us?](http://farmdocdaily.illinois.edu/2015/02/expectations-for-2015-us-average-corn-yield.html)

    - Irwin, S., and D. Good. "Forming Expectations for the 2015 U.S. Average Corn Yield: What Does History Teach Us?" farmdoc daily (5):36, Department of Agricultural and Consumer Economics, University of Illinois at Urbana-Champaign, February 26, 2015.

2. Break at 1pm to watch market reaction to Fed decision

3. Read and Discuss: [Early Planting and 2015 Corn Yield Prospects: How Much of an Increase?](http://farmdocdaily.illinois.edu/2015/05/early-planting-and-2015-corn-yield-prospects.html)

    - Irwin, S., D. Good, and J. Newton. "Early Planting and 2015 Corn Yield Prospects: How Much of an Increase?" farmdoc daily (5):93, Department of Agricultural and Consumer Economics, University of Illinois at Urbana-Champaign, May 20, 2015.
    
#  Forming Expectations for the 2015 U.S. Average Corn Yield: What Does History Teach Us?

## Main Points of Discussion

1. Likelihood of above versus below trend. Relative size of above- and below-trend deviations
2. Current Year - Previous Year correlations
3. Runs of above- versus below-trend years
4. Frequency Distribution of Trend Adjusted Historical Deviations

# Break for Fed Watching!

# Early Planting and 2015 Corn Yield Prospects: How Much of an Increase? 

## Main Points of Discussion

1. Yield Response to Corn Planting Date
2. Relationship between percent planted late and early
3. Historical Percent Planted Late
4. Yield Penalty for Percent Planted Late

