---
title: "Preface"
output: md_document
---

I am writing *Commodity Price Analysis: Understand and Produce Market Commentary and Forecasts* and *R Companion to Commodity Price Analysis* while teaching ACE 427, an upper level course on Price Analysis at the University of Illinois. The books are intended to be read together, but one could read *Commodity Price Analysis* without reading the *R Companion*. I am writing them as separate books because I can imagine professors teaching Price Analysis may not want to use R for analysis. In this case they could use *Commodity Price Analysis* in their course and do analysis in the software package of their choice. 

I am releasing these books while they are very early in development. Partly because the Lean Publishing model of 'Publish Early, Publish Often' (with reader feedback) appeals to me. Another concern is purely practical. I want to use this book for classes in Fall 2015 and chapters will be finished only shortly before I assign readings and exercises. Because the book is in its early development stage, expect typos and other errors in the books. Knowing this, I am releasing the book for free, at least through December. During this time I will be rapidly releasing updates to keep up with my course. 

I am eager to hear reader feedback about the structure and scope of the books; I will appreciate any feedback you have. If you find errors, please alert me via the [Leanpub](http://leanpub.com). 

Mindy Mallory