---
title: "MakeBookAssets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)


# Color Schemes:

purduegold <- '#CEB888'
```

# This file creates assets for my price analysis book. Code can be run to update figures and tables in the book. Assets are located in the `/assets` subdirectory. 

# Graphs for `041-Options1.Rmd`

```{r}
prices <- data.frame(price = 400:500)
strike = 450
prem = 10

prices <- prices %>% 
  mutate(callpayoffs = pmax(price - strike, 0) - prem) %>% 
  mutate(putpayoffs = pmax(strike - price, 0) - prem)

longcall <- ggplot(prices, aes(x = price, y = callpayoffs)) + 
  geom_line(size = 1.5, color = purduegold) +
  theme_bw() + 
  geom_hline(yintercept = 0) + 
  lims(y = c(-40, 40)) +
  labs(title = "Long Call", x = "", y = "Profit or Loss cents/contract") + 
  theme(plot.title = element_text(hjust = 0.5))

longput <- ggplot(prices, aes(x = price, y = putpayoffs)) + 
  geom_line(size = 1.5, color = purduegold) +
  theme_bw() + 
  geom_hline(yintercept = 0) + 
  lims(y = c(-40, 40)) +
  labs(title = "Long Put", x = "", y = "") + 
  theme(plot.title = element_text(hjust = 0.5))

shortcall <- ggplot(prices, aes(x = price, y = -callpayoffs)) + 
  geom_line(size = 1.5, color = purduegold) +
  theme_bw() + 
  geom_hline(yintercept = 0) + 
  lims(y = c(-40, 40)) +
  labs(title = "Short Call", x = "Price of Underlying cents/contract", y = "Profit or Loss cents/contract") + 
  theme(plot.title = element_text(hjust = 0.5))

shortput <- ggplot(prices, aes(x = price, y = -putpayoffs)) + 
  geom_line(size = 1.5, color = purduegold) +
  theme_bw() + 
  geom_hline(yintercept = 0) + 
  lims(y = c(-40, 40)) +
  labs(title = "Short Put", x = "Price of Underlying cents/contract", y = "") + 
  theme(plot.title = element_text(hjust = 0.5))

figure <- ggarrange(longcall, longput, shortcall, shortput)

figure <- annotate_figure(figure, 
                top = text_grob("Option Profit Diagrams at Expiration", 
                                face = "bold", 
                                size = 14))
ggsave(filename = "Options1-optionplot.png")


```

```{r, fig.width= 6, fig.hight = 4}
prices <- data.frame(price = 1000:1400)
strike = 1200
premc = 47.875
premp = 0.375

prices <- prices %>% 
  mutate(callpayoffs = pmax(price - strike, 0) - premc) %>% 
  mutate(putpayoffs = pmax(strike - price, 0) - premp)

longcall <- ggplot(prices, aes(x = price, y = callpayoffs)) + 
  geom_line(size = 1.5, color = purduegold) +
  theme_bw() + 
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 1250) +
  lims(y = c(-60, 60)) +
  labs(title = "Long Call", x = "", y = "Profit or Loss cents/contract") + 
  theme(plot.title = element_text(hjust = 0.5))

longput <- ggplot(prices, aes(x = price, y = putpayoffs)) + 
  geom_line(size = 1.5, color = purduegold) +
  theme_bw() + 
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 1250) +
  lims(y = c(-60, 60)) +
  labs(title = "Long Put", x = "", y = "") + 
  theme(plot.title = element_text(hjust = 0.5))

figure <- ggarrange(longcall, longput)

figure <- annotate_figure(figure, 
                top = text_grob("Option Profit Diagrams at Expiration, 1200 Strikes", 
                                face = "bold", 
                                size = 14))
figure

ggsave(filename = "Options1-optionmoneynessplot.png")

```

```{r, fig.width= 6, fig.hight = 4}
prices <- data.frame(price = 400:500)
strike = 450
premc = 0
premp = 0

prices <- prices %>% 
  mutate(callpayoffs = pmax(price - strike, 0) - premc) %>% 
  mutate(putpayoffs = pmax(strike - price, 0) - premp)

longcall <- ggplot(prices, aes(x = price, y = callpayoffs)) + 
  geom_line(size = 1.5, color = purduegold) +
  theme_bw() + 
  geom_hline(yintercept = 0) + 
  lims(y = c(-15, 60)) +
  labs(title = "Long Call", x = "", y = "Profit or Loss cents/contract") + 
  theme(plot.title = element_text(hjust = 0.5))

longput <- ggplot(prices, aes(x = price, y = putpayoffs)) + 
  geom_line(size = 1.5, color = purduegold) +
  theme_bw() + 
  geom_hline(yintercept = 0) + 
  lims(y = c(-15, 60)) +
  labs(title = "Long Put", x = "", y = "") + 
  theme(plot.title = element_text(hjust = 0.5))

figure <- ggarrange(longcall, longput)

figure <- annotate_figure(figure, 
                top = text_grob("Option Payoff Diagrams, 450 Strikes", 
                                face = "bold", 
                                size = 14))
figure

ggsave(filename = "Options1-optionintrinsic.png")

```




# Figures for "PrimerforGrain.rmd"

```{r}
key = 'BD652A51-1B61-3442-B80A-9B4030E2F382'

library(rnassqs)
# apikey <- "YOUR API KEY"
nassqs_auth(key)

params1 <- list(commodity_desc = c("CORN", "SOYBEANS", "WHEAT"), 
                year__GE = 1926, 
                agg_level_desc = "NATIONAL", 
                statisticcat_desc = c("YIELD", "Area Planted", "Production", "PRICE RECEIVED"),
                prodn_practice_desc = "ALL PRODUCTION PRACTICES",
                util_practice_desc = c("GRAIN", "ALL UTILIZATION PRACTICES"),
                reference_period_desc = c("YEAR", "Marketing Year"),
                freq_desc = "ANNUAL"
                #prodn_practice_desc = "NON-IRRIGATED"
                ) # GE means "greater than or equal to"
data1   <- nassqs(params1)
data1$Value <- as.numeric(gsub(",", "", as.character(data1$Value)))


corn1 <- data1 %>% 
  select(c(commodity_desc, statisticcat_desc, short_desc, year, Value )) %>%
  filter( commodity_desc == "CORN") %>%
  filter(statisticcat_desc == "AREA PLANTED") %>%
  ggplot(aes(x = year, y = Value/1000000)) + 
  geom_col(width = .7) +
  geom_line(data = data1 %>% 
  select(c(commodity_desc, statisticcat_desc, short_desc, year, Value )) %>%
  filter( commodity_desc == "CORN") %>%
  filter(statisticcat_desc == "YIELD"), aes(x = year, y = Value), color = purduegold, size = 1.5) +
  theme_bw() +
  lims(y = c(0, 200)) +
  labs(title = "U.S. Corn Acreage and Yield", x = "", y = "Millions of Acres, and Bu/Acre, respectively") + 
  scale_x_continuous(n.breaks = 25)

corn1  
ggsave(corn1, filename = "PrimerforGrain_CornAcandY.png")



corn2 <- data1 %>% 
  filter( commodity_desc == "CORN") %>%
  filter(statisticcat_desc == "PRODUCTION") %>%
  filter(short_desc == "CORN, GRAIN - PRODUCTION, MEASURED IN BU") %>%
  filter( domaincat_desc == "NOT SPECIFIED") %>% 
  filter(source_desc == "SURVEY") %>%
  select(c(commodity_desc, statisticcat_desc, short_desc, domaincat_desc, source_desc, year, Value )) %>% 
  ggplot(aes(x = year, y = Value/1000000000)) + 
  geom_col(width = 1.0) +
  geom_line(data = data1 %>% 
  filter( commodity_desc == "CORN") %>%
  filter(statisticcat_desc == "PRICE RECEIVED") %>%
  filter(reference_period_desc == "MARKETING YEAR") %>% 
  filter(short_desc == "CORN, GRAIN - PRICE RECEIVED, MEASURED IN $ / BU") %>% 
 select(c(commodity_desc, statisticcat_desc, short_desc, year, Value )), aes(x = year, y = Value), color = purduegold, size = 1.5) +
  theme_bw() +
  lims(y = c(0, 16)) +
  labs(title = "U.S. Corn Production and Prices", x = "", y = "Billions of Bushels, and $/bu, respectively") + 
  scale_x_continuous(n.breaks = 25)
  
#+
 # scale_y_continuous(
#    name = "$/bu", 
 #   sec.axis = sec_axis(~ . * 1.5  , name = "Billions of Bushels"), 
  #  limits = c(0, 17)) 

corn2
ggsave(corn2, filename = "PrimerforGrain_CornProdand$.png")

```


```{r}
soy1 <- data1 %>% 
  select(c(commodity_desc, statisticcat_desc, short_desc, year, Value )) %>%
  filter( commodity_desc == "SOYBEANS") %>%
  filter(statisticcat_desc == "AREA PLANTED") %>%
  ggplot(aes(x = year, y = Value/1000000)) + 
  geom_col(width = 1) +
  geom_line(data = data1 %>% 
  select(c(commodity_desc, statisticcat_desc, short_desc, year, Value )) %>%
  filter( commodity_desc == "SOYBEANS") %>%
  filter(statisticcat_desc == "YIELD"), aes(x = year, y = Value), color = purduegold, size = 1.5) +
  theme_bw() +
  lims(y = c(0, 100)) +
  labs(title = "U.S. Soybean Acreage and Yield", x = "", y = "Millions of Acres, and Bu/Acre, respectively") + 
  scale_x_continuous(n.breaks = 25)

soy1  
ggsave(soy1, filename = "PrimerforGrain_SoyAcandY.png")



soy2 <- data1 %>% 
  filter( commodity_desc == "SOYBEANS") %>%
  filter(statisticcat_desc == "PRODUCTION") %>%
  filter(short_desc == "SOYBEANS - PRODUCTION, MEASURED IN BU") %>%
  filter( domaincat_desc == "NOT SPECIFIED") %>% 
  filter(source_desc == "SURVEY") %>%
  select(c(commodity_desc, statisticcat_desc, short_desc, domaincat_desc, source_desc, year, Value )) %>% 
  ggplot(aes(x = year, y = Value/1000000000)) + 
  geom_col(width = 1.0) +
  geom_line(data = data1 %>% 
  filter( commodity_desc == "SOYBEANS") %>%
  filter(statisticcat_desc == "PRICE RECEIVED") %>%
  filter(reference_period_desc == "MARKETING YEAR") %>% 
  filter(short_desc == "SOYBEANS - PRICE RECEIVED, MEASURED IN $ / BU") %>% 
 select(c(commodity_desc, statisticcat_desc, short_desc, year, Value )), aes(x = year, y = Value), color = purduegold, size = 1.5) +
  theme_bw() +
  lims(y = c(0, 16)) +
  labs(title = "U.S. Soybean Production and Prices", x = "", y = "Billions of Bushels, and $/bu, respectively") + 
  scale_x_continuous(n.breaks = 25)
  
#+
 # scale_y_continuous(
#    name = "$/bu", 
 #   sec.axis = sec_axis(~ . * 1.5  , name = "Billions of Bushels"), 
  #  limits = c(0, 17)) 

soy2
ggsave(soy2, filename = "PrimerforGrain_SoyProdand$.png")


```

```{r}
wheat1 <- data1 %>%  
  select(c(commodity_desc, statisticcat_desc, short_desc, year, Value )) %>%
  filter( commodity_desc == "WHEAT") %>%
  filter(short_desc == "WHEAT - ACRES PLANTED") %>%  
  filter(statisticcat_desc == "AREA PLANTED") %>%
  ggplot(aes(x = year, y = Value/1000000)) + 
  geom_col(width = 1) +
  geom_line(data = data1 %>% 
  select(c(commodity_desc, statisticcat_desc, short_desc, year, Value )) %>%
  filter( commodity_desc == "WHEAT") %>%
  filter(short_desc == "WHEAT - YIELD, MEASURED IN BU / ACRE") %>%
  filter(statisticcat_desc == "YIELD"), aes(x = year, y = Value), color = purduegold, size = 1.5) +
  theme_bw() +
  lims(y = c(0, 100)) +
  labs(title = "U.S. Wheat Acreage and Yield", x = "", y = "Millions of Acres, and Bu/Acre, respectively") + 
  scale_x_continuous(n.breaks = 25)

wheat1  
ggsave(wheat1, filename = "PrimerforGrain_WheatAcandY.png")



wheat2 <- data1 %>% 
  filter( commodity_desc == "WHEAT") %>%
  filter(statisticcat_desc == "PRODUCTION") %>%
  filter(short_desc == "WHEAT - PRODUCTION, MEASURED IN BU") %>%
  filter( domaincat_desc == "NOT SPECIFIED") %>% 
  filter(source_desc == "SURVEY") %>%
  select(c(commodity_desc, statisticcat_desc, short_desc, domaincat_desc, source_desc, year, Value )) %>% 
  ggplot(aes(x = year, y = Value/1000000000)) + 
  geom_col(width = 1.0) +
  geom_line(data = data1 %>% 
  filter( commodity_desc == "WHEAT") %>%
  filter(statisticcat_desc == "PRICE RECEIVED") %>%
  filter(reference_period_desc == "MARKETING YEAR") %>% 
  filter(short_desc == "WHEAT - PRICE RECEIVED, MEASURED IN $ / BU") %>% 
 select(c(commodity_desc, statisticcat_desc, short_desc, year, Value )), aes(x = year, y = Value), color = purduegold, size = 1.5) +
  theme_bw() +
  lims(y = c(0,9)) +
  labs(title = "U.S. Wheat Production and Prices", x = "", y = "Billions of Bushels, and $/bu, respectively") + 
  scale_x_continuous(n.breaks = 25)
  
#+
 # scale_y_continuous(
#    name = "$/bu", 
 #   sec.axis = sec_axis(~ . * 1.5  , name = "Billions of Bushels"), 
  #  limits = c(0, 17)) 

wheat2
ggsave(wheat2, filename = "PrimerforGrain_WheatProdand$.png")


```



```{r}
library(tidyverse)
library(readxl)
library(httr)
library(tidyr)


tmp <- tempfile(fileext = ".xls")

httr::GET(url = "https://www.ers.usda.gov/webdocs/DataFiles/50048/Feed%20Grains%20Yearbook%20Tables-All%20Years.xls",
          write_disk( tmp, overwrite = TRUE) )

data_xl <- read_excel(tmp, sheet = "FGYearbookTable04-Full", 
                      skip = 4, 
                      col_names = c("MktYear", "Quarter", "BeginningStocks", "Production", "Imports", 
                                    "TotalSupply", "FoodAlcoholInd", "Seed", "FeedandResidual", 
                                    "TotalDomestic", "Exports", "TotalUse", "EndingStocks")) %>%
  fill(MktYear) %>% 
  # Make columns for more standard date handling
  mutate(month = ifelse(Quarter =="Q1 Sep-Nov", "09-01", 
                        ifelse(Quarter == "Q2 Dec-Feb", "12-01", 
                               ifelse(Quarter == "Q3 Mar-May", "03-01", 
                                      ifelse(Quarter == "Q4 Jun-Aug", "06-01",
                                             ifelse(Quarter == "MY Sep-Aug", "09-01", NA)))))) %>%
  mutate(year = ifelse(Quarter =="Q1 Sep-Nov" | Quarter == "Q2 Dec-Feb" | Quarter == "MY Sep-Aug", as.numeric(str_sub(MktYear, 1,4)), 
                       as.numeric(str_sub(MktYear, 1,4)) +1 )) %>%
  mutate(date = as.Date(paste0(as.character(year), "-", month))) # Now we have a proper date column.

# Make tidy getting ready for ggplot
data_tidy <- data_xl %>% 
  select(c(-MktYear, -month, -year)) %>%
  pivot_longer(c(-date, -Quarter), names_to = "UseCategory", values_to = "Value")

data_tidy

# Plot the Marketing Year Data
CornUse <- data_tidy %>% filter(Quarter == "MY Sep-Aug") %>%
  filter(UseCategory %in% c("FoodAlcoholInd", "Seed", "FeedandResidual", "Exports", "EndingStocks")) %>%
  ggplot(aes(x = date, y = Value, fill = UseCategory)) + 
  geom_area() + 
  theme_bw() +
  labs(x = "", y = "Millions of bushels", title = "Corn Use Categories Since 1975")


CornUse
ggsave(CornUse, filename = "PrimerforGrain_CornUse.png")

```


```{r}
tmp1 <- tempfile(fileext = ".xlsx")

httr::GET(url = "https://www.ers.usda.gov/webdocs/DataFiles/52218/OilCropsAllTables.xlsx?v=3685",
          write_disk( tmp1) )



data_xl <- read_excel(tmp1, sheet = "tab3", 
                     skip = 6, 
                      col_names = c("MktYear", "BeginningStocks", "Production", "Imports", 
                                    "TotalSupply", "Crush", "Exports", "SeedFeedandResidual", 
                                    "Total", "EndingStocks", "Prices")) 

# Make tidy getting ready for ggplot
data_xl$Prices <- as.numeric(data_xl$Prices)
data_xl <- data_xl[1:39,]  # Increase this by one to update. Have to cut off junk at bottom
data_xl$MktYear <- as.numeric(data_xl$MktYear)
data_tidy <- data_xl %>% 
  pivot_longer(c(-MktYear), names_to = "UseCategory", values_to = "Value")


data_tidy

# Plot the Marketing Year Data
SoybeanUse <- data_tidy %>% 
  filter(UseCategory %in% c("Crush", "Exports", "SeedFeedandResidual", "EndingStocks")) %>%
  ggplot(aes(x = MktYear, y = Value, fill = UseCategory)) + 
  geom_area() + 
  theme_bw() +
  labs(x = "", y = "Millions of bushels", title = "Soybean Use Categories Since 1980") +
   scale_x_continuous(n.breaks = 10)

SoybeanUse
ggsave(SoybeanUse, filename = "PrimerforGrain_SoyUse.png")


```

```{r}
CornPrices<- data1 %>% 
  filter( commodity_desc == "CORN") %>%
  filter(statisticcat_desc == "PRICE RECEIVED") %>%
  filter(reference_period_desc == "MARKETING YEAR") %>% 
  filter(short_desc == "CORN, GRAIN - PRICE RECEIVED, MEASURED IN $ / BU") %>% 
 select(c(commodity_desc, statisticcat_desc, short_desc, year, Value )) %>% 
  ggplot(aes(x = year, y = Value)) + 
  geom_line(color = purduegold, size = 1.5) +
  theme_bw() +
  lims(y = c(0, 8)) +
  labs(title = "U.S. Corn Prices", x = "", y = "$/bu") + 
  scale_x_continuous(n.breaks = 25)

CornPrices
ggsave(CornPrices, filename = "PrimerforGrain_CornPrices.png")
```







# Figures for `05-PricesSpaceTime.Rmd`


```{r, echo = FALSE, message = FALSE, warning=FALSE}
library(tidyr)
library(ggplot2)

df <- tibble(xaxis = c("Dec", "Mar", "May", "Jul", "Sep", "Dec2"),
             day = c('day 1', 'day 1', 'day 1', 'day 1', 'day 1', 'day 1'),
             price = c(330, 340, 345, 353, 360, 370))

df$xaxis <- factor(df$xaxis, levels = unique(df$xaxis[order(df$price)]))

g <- ggplot(df, aes(xaxis, price)) + ylim(300,425) + theme_bw() +
        geom_point() + 
        geom_line(aes(group = day)) +
        scale_color_manual(values = c(purduegold, purduegold, purduegold, purduegold, purduegold, purduegold)) +
        labs(title = "Increasing Forward Curve from Sep 26, 2016", x = "", y = "Price cents per bushel") 
        
g       
ggsave(filename = "PricesSpaceTime-increasing-9-26-2016.png")



df <- tibble(xaxis = c("Dec", "Mar", "May", "Jul", "Sep", "Dec2"),
             day = c('day 1', 'day 1', 'day 1', 'day 1', 'day 1', 'day 1'),
             price = c(390, 400, 408, 412, 405, 410))

df$xaxis <- factor(df$xaxis, levels = unique(df$xaxis))

g <- ggplot(df, aes(xaxis, price)) + ylim(375,415) + theme_bw() +
        geom_point() + 
        geom_line(aes(group = day)) +
        scale_color_manual(values = c(purduegold, purduegold, purduegold, purduegold, purduegold, purduegold)) +
        labs(title = "Increasing Forward Curve from Sep 25, 2015", x = "", y = "Price cents per bushel") 
        
       
g
ggsave(filename = "PricesSpaceTime-increasing-9-25-2015.png")


df <- tibble(xaxis = c("May", "Jul", "Sep", "Dec", "Mar", "May2"),
             day = c('day 1', 'day 1', 'day 1', 'day 1', 'day 1', 'day 1'),
             price = c(630, 620, 555, 540, 545, 555))

df$xaxis <- factor(df$xaxis, levels = unique(df$xaxis))

g <- ggplot(df, aes(xaxis, price)) + ylim(480,640) + theme_bw() +
        geom_point() + 
        geom_line(aes(group = day)) +
        scale_color_manual(values = c(purduegold, purduegold, purduegold, purduegold, purduegold, purduegold)) +
        labs(title = "Decreasing Forward Curve from Apr 13, 2012", x = "", y = "Price cents per bushel") 
        
       
g
ggsave(filename = "PricesSpaceTime-decreasing-4-13-2012.png")



df <- tibble(xaxis = c("Sep", "Dec", "Mar", "May", "Jul", "Sep2", "Dec2"),
             day = c('day 1', 'day 1', 'day 1', 'day 1', 'day 1', 'day 1', 'day 1'),
             price = c(800, 800, 800, 799, 797, 698, 610))

df$xaxis <- factor(df$xaxis, levels = unique(df$xaxis))

g <- ggplot(df, aes(xaxis, price)) + ylim(500,900) + theme_bw() +
        geom_point() + 
        geom_line(aes(group = day)) +
        scale_color_manual(values = c(purduegold, purduegold, purduegold, purduegold, purduegold, purduegold)) +
        labs(title = "Flat Forward Curve from Aug 1, 2012", x = "", y = "Price cents per bushel") 
        
       
g
ggsave(filename = "PricesSpaceTime-flat-8-01-2012.png")


df <- tibble(xaxis = c("Dec", "Mar", "May", "Jul", "Sep2", "Dec2"),
             day = c('day 1', 'day 1', 'day 1', 'day 1', 'day 1', 'day 1' ),
             price = c(745, 755, 754, 740, 660, 640))

df$xaxis <- factor(df$xaxis, levels = unique(df$xaxis))

g <- ggplot(df, aes(xaxis, price)) + ylim(500,900) + theme_bw() +
        geom_point() + 
        geom_line(aes(group = day)) +
        scale_color_manual(values = c(purduegold, purduegold, purduegold, purduegold, purduegold, purduegold)) +
        labs(title = "Flat and Falling Forward Curve from Dec 3, 2012", x = "", y = "Price cents per bushel") 
        
       
g
ggsave(filename = "PricesSpaceTime-flat-12-03-2012.png")

xaxis <- c('Dec', 'March', 'May', 'July', 'Sept')
day1 <- c('day 1', 'day 1', 'day 1', 'day 1', 'day 1')
day2 <- c('day 2', 'day 2', 'day 2', 'day 2', 'day 2')
day3 <- c('day 3', 'day 3', 'day 3', 'day 3', 'day 3')
day4 <- c('day 4', 'day 4', 'day 4', 'day 4', 'day 4')
day1p <- as.numeric(c(350, 360, 369, 375, 378))
day2p <- as.numeric(c(355, 364, 372, 377, 379))
day3p <- as.numeric(c(360, 367, 374, 378, 380))
day4p <- as.numeric(c(385, 383, 382, 381, 381))

day1 <- cbind(xaxis, day1, day1p)
day2 <- cbind(xaxis, day2, day2p)
day3 <- cbind(xaxis, day3, day3p)
day4 <- cbind(xaxis, day4, day4p)
df <- rbind(day1, day2, day3, day4)
df <- as.data.frame(df)
colnames(df) <- c('xaxis', 'day', 'price')
# df$xaxis <- factor(df$xaxis, levels = df$xaxis[order(df$price)])
df$xaxis <- factor(df$xaxis, levels = unique(df$xaxis[order(df$price)]))

df$price <- as.numeric(as.character(df$price))
g <- ggplot(df, aes(xaxis, price, colour= day)) + ylim(300,425) + theme_bw() +
        geom_point() + geom_line(aes(group = day)) +
        scale_color_manual(values = c("darkblue", "darkblue", "darkblue", "darkblue")) +
        labs(x = "", y = "Price cents per bushel") + 
        geom_text(aes(label= ifelse(xaxis == "Dec", as.character(day), '')),hjust=1.5, vjust=0) + 
        theme(legend.position = "none")
       
g
ggsave(filename = "PricesSpaceTime-pricesincreasing-hyp.png")


xaxis <- c('Dec', 'March', 'May', 'July', 'Sept')
day1 <- c('day 1', 'day  1', 'day 1', 'day 1', 'day 1')
day2 <- c('day 2', 'day 2', 'day 2', 'day 2', 'day 2')
day3 <- c('day 3', 'day 3', 'day 3', 'day 3', 'day 3')
day4 <- c('day 4', 'day 4', 'day 4', 'day 4', 'day 4')
day1p <- as.numeric(c(350, 360, 369, 375, 378))
day2p <- as.numeric(c(342, 354, 366, 372, 377))
day3p <- as.numeric(c(332, 346, 360, 368, 374))
day4p <- as.numeric(c(327, 341, 355, 363, 369))

day1 <- cbind(xaxis, day1, day1p)
day2 <- cbind(xaxis, day2, day2p)
day3 <- cbind(xaxis, day3, day3p)
day4 <- cbind(xaxis, day4, day4p)
df <- rbind(day1, day2, day3, day4)
df <- as.data.frame(df)
colnames(df) <- c('xaxis', 'day', 'price')
# df$xaxis <- factor(df$xaxis, levels = df$xaxis[order(df$price)])
df$xaxis <- factor(df$xaxis, levels = unique(df$xaxis[order(df$price)]))
df$price <- as.numeric(as.character(df$price))
g <- ggplot(df, aes(xaxis, price, colour= day)) + ylim(300,425) + theme_bw() +
        geom_point() + geom_line(aes(group = day)) +
        scale_color_manual(values = c("darkblue", "darkblue", "darkblue", "darkblue", "darkblue")) +
        labs(x = "", y = "Price cents per bushel") + 
        geom_text(aes(label= ifelse(xaxis == "Dec", as.character(day), '')),hjust=1.5, vjust=0) + 
        theme(legend.position = "none")
       
g
ggsave(filename = "PricesSpaceTime-pricesdecreasing-hyp.png")

```




# Figures for `08-ForecastingProduction.Rmd`

```{r, fig.width = 6, fig.height= 5}
nassqs_auth(key)

params1 <- list(commodity_desc = c("CORN", "SOYBEANS", "WHEAT"), 
                year__GE = 1926, 
                agg_level_desc = "NATIONAL", 
                statisticcat_desc = c("YIELD", "Area Planted", "Area Harvested", "Production", "PRICE RECEIVED"),
                prodn_practice_desc = "ALL PRODUCTION PRACTICES",
                util_practice_desc = c("GRAIN", "ALL UTILIZATION PRACTICES"),
                reference_period_desc = c("YEAR", "Marketing Year"),
                freq_desc = "ANNUAL"
                #prodn_practice_desc = "NON-IRRIGATED"
                ) # GE means "greater than or equal to"
data1   <- nassqs(params1)
data1$Value <- as.numeric(gsub(",", "", as.character(data1$Value)))
data1

corn2 <- data1 %>% 
  filter( commodity_desc == "CORN" | commodity_desc == "SOYBEANS") %>%
  filter(statisticcat_desc == "AREA PLANTED") %>%
  #filter(short_desc == "CORN, GRAIN - PRODUCTION, MEASURED IN BU") %>%
  filter( domaincat_desc == "NOT SPECIFIED") %>% 
  filter(source_desc == "SURVEY") %>%
  select(c(commodity_desc, statisticcat_desc, short_desc, domaincat_desc, source_desc, year, Value )) %>% 
  ggplot(aes(x = year, y = Value/1000000, color = commodity_desc)) + 
  geom_line() +
  geom_line(data = data1 %>% 
    filter( commodity_desc == "CORN" | commodity_desc == "SOYBEANS") %>%
    filter(statisticcat_desc == "PRICE RECEIVED") %>%
    filter(reference_period_desc == "MARKETING YEAR") %>% 
    select(c(commodity_desc, year, Value )) %>% 
    pivot_wider(names_from = "commodity_desc", values_from = "Value", values_fn = {mean}) %>% 
    mutate(CornSoyRatio = lead(CORN, 2)/lead(SOYBEANS, 2)*100), 
     aes(x = year, y = CornSoyRatio, color = "Last-Year-Corn/Soy-PriceRatio")) +
  theme_bw() +
  #lims(y = c(0, 16)) +
  labs(title = "U.S. Corn and Soybeans Planted Acres", x = "", y = "Millions of Acres") + 
  scale_x_continuous(n.breaks = 15)
  
corn2

ggsave(filename = "ForecastingProduction-PlantedAcres.png")


corn <- read.csv("zcz17.csv") %>% select( timestamp, close)
soybeans <- read.csv("zsx17.csv") %>% select( timestamp, close)
       
temp <- inner_join(corn, soybeans, by = "timestamp")
colnames(temp) <- c("timestamp", "Corn", "Soybeans")

 
temp %>% mutate(CornSoyRatio = Corn/Soybeans*100) %>%
  mutate(timestamp = as.Date(timestamp)) %>% 
  filter(timestamp < as.Date("2017-07-01")) %>%
  ggplot(aes(x = timestamp, y = CornSoyRatio)) +
   geom_line() +
  theme_bw() +
  #lims(y = c(0, 16)) +
  labs(title = "2017 Harvest Price Ratio Corn and Soybeans", x = "", y = "Corn/Soy*100")

ggsave(filename = "ForecastingProduction-PriceRatio.png")


corn2 <- data1 %>% 
  filter( commodity_desc == "CORN" ) %>%
  filter(statisticcat_desc == "AREA PLANTED" | statisticcat_desc == "AREA HARVESTED") %>%
  filter( domaincat_desc == "NOT SPECIFIED") %>% 
  filter(source_desc == "SURVEY") %>%
  select(c(year, commodity_desc, statisticcat_desc, Value )) %>% 
  filter(year > 1998) %>% 
  pivot_wider(names_from = 'statisticcat_desc', values_from = "Value") %>%
  mutate(DIFFERENCE = `AREA PLANTED` - `AREA HARVESTED`) %>% 
  pivot_longer(cols = c("AREA PLANTED", "AREA HARVESTED", "DIFFERENCE"), names_to = "ACRES") %>%
  ggplot(aes(x = year, y = value/1000000, color = ACRES)) + 
  geom_line() +
  theme_bw() +
  scale_x_continuous(n.breaks = 5) +
  #lims(y = c(0, 16)) +
  labs(title = "Corn Planted Acres and Harvested Acres Since 1999", x = "", y = "Millions of Acres")

corn2
ggsave(filename = "ForecastingProduction-PAHA.png")
```




