<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Price Analysis: A Fundamental Approach to the Study of Commodity Prices - 17&nbsp; Ethanol</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./18-BeefCattleMarkets.html" rel="next">
<link href="./16-TheSoybeanCrush.html" rel="prev">
<link href="./cover.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-8C738FZXS8"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-8C738FZXS8', { 'anonymize_ip': true});
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Price Analysis: A Fundamental Approach to the Study of Commodity Prices - 17&nbsp; Ethanol">
<meta property="og:description" content="">
<meta property="og:image" content="http://mindymallory.com/PriceAnalysis/images/eth_locations.png">
<meta property="og:site-name" content="Price Analysis: A Fundamental Approach to the Study of Commodity Prices">
<meta property="og:image:height" content="876">
<meta property="og:image:width" content="1871">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./17-EthanolMarketsand.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Ethanol</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Price Analysis: A Fundamental Approach to the Study of Commodity Prices</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/mindymallory/PriceAnalysis" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Price-Analysis--A-Fundamental-Approach-to-the-Study-of-Commodity-Prices.pdf">
              <i class="bi bi-bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Price-Analysis--A-Fundamental-Approach-to-the-Study-of-Commodity-Prices.epub">
              <i class="bi bi-bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-PrimerforGrain.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Grain and Oilseed Markets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-IntroductiontoCommodity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Commodity Price Analysis and Forecasting</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-HowtoFind.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">How to Find Information</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-FuturesContractsandHedging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Futures and Hedging Review</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Options1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Introduction to Option Contracts</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Options2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Advanced Option Topics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Options4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hedging with Options</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-Options3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Marketing, Hedging, and Crop Insurance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-PricesSpaceTime.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Prices Over Space and Time</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FundamentalAnalysisand.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Balance Sheet Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-PriceReactionto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Price Reaction to USDA Reports</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-ForecastingProduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Price Reaction to USDA Reports</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-ForecastingUseof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Forecasting Use of Corn</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-ForecastingUseSoy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Forecasting Use of Soybeans</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-EndingStocksand.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Ending Stocks and Price</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-TheSoybeanCrush.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">The Soybean Crush</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-EthanolMarketsand.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Ethanol</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-BeefCattleMarkets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Cattle Markets and the Livestock Crush</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-HogMarkets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Hog Markets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-CrudeOiland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Crude Oil and the Crack Spread</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-ForecastingProductionAdvanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Forecasting Production - Advanced</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-IntroductiontoCommodityTS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Appendix: Forecasting with TS Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-IntroductiontoSingle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Appendix: Single Market Models: ARIMA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-A-South-American-Production.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">South American Production</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#ethanol-production" id="toc-ethanol-production" class="nav-link active" data-scroll-target="#ethanol-production"><span class="header-section-number">17.1</span> Ethanol Production</a>
  <ul class="collapse">
  <li><a href="#dry-grind-ethanol-production" id="toc-dry-grind-ethanol-production" class="nav-link" data-scroll-target="#dry-grind-ethanol-production"><span class="header-section-number">17.1.1</span> Dry Grind Ethanol Production</a></li>
  <li><a href="#wet-grind-ethanol-production" id="toc-wet-grind-ethanol-production" class="nav-link" data-scroll-target="#wet-grind-ethanol-production"><span class="header-section-number">17.1.2</span> Wet Grind Ethanol Production</a></li>
  </ul></li>
  <li><a href="#distillers-grains" id="toc-distillers-grains" class="nav-link" data-scroll-target="#distillers-grains"><span class="header-section-number">17.2</span> Distiller’s Grains</a>
  <ul class="collapse">
  <li><a href="#ddg-prices" id="toc-ddg-prices" class="nav-link" data-scroll-target="#ddg-prices"><span class="header-section-number">17.2.1</span> DDG Prices</a></li>
  </ul></li>
  <li><a href="#ethanol-prices" id="toc-ethanol-prices" class="nav-link" data-scroll-target="#ethanol-prices"><span class="header-section-number">17.3</span> Ethanol Prices</a></li>
  <li><a href="#ethanol-and-gas-prices" id="toc-ethanol-and-gas-prices" class="nav-link" data-scroll-target="#ethanol-and-gas-prices"><span class="header-section-number">17.4</span> Ethanol and Gas Prices</a></li>
  <li><a href="#ethanol-crush-spread" id="toc-ethanol-crush-spread" class="nav-link" data-scroll-target="#ethanol-crush-spread"><span class="header-section-number">17.5</span> Ethanol Crush Spread</a></li>
  <li><a href="#hedging-the-crush-spread" id="toc-hedging-the-crush-spread" class="nav-link" data-scroll-target="#hedging-the-crush-spread"><span class="header-section-number">17.6</span> Hedging the Crush Spread</a></li>
  <li><a href="#cross-hedging" id="toc-cross-hedging" class="nav-link" data-scroll-target="#cross-hedging"><span class="header-section-number">17.7</span> Cross Hedging</a>
  <ul class="collapse">
  <li><a href="#minimize-the-variance-of-cash-flow-with-optimal-hedge-ratio-for-ddgs-and-corn-futures" id="toc-minimize-the-variance-of-cash-flow-with-optimal-hedge-ratio-for-ddgs-and-corn-futures" class="nav-link" data-scroll-target="#minimize-the-variance-of-cash-flow-with-optimal-hedge-ratio-for-ddgs-and-corn-futures"><span class="header-section-number">17.7.1</span> Minimize the Variance of Cash Flow with Optimal Hedge Ratio for DDGs and Corn Futures</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">17.8</span> Exercises</a></li>
  <li><a href="#readings" id="toc-readings" class="nav-link" data-scroll-target="#readings"><span class="header-section-number">17.9</span> Readings</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/mindymallory/PriceAnalysis/edit/main/17-EthanolMarketsand.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Ethanol</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><span style="color:red">Interested in more? Please let me know by</span> <a href="https://forms.gle/Q3VByCQZHjfQSy9D7">taking the survey</a>!</p>
<p>Ethanol production and consumption begin to increase rapidly around 2005, which is when the Energy Policy Act of 2005 and later the Energy Security and Independence Act of 2007 created the Renewable Fuels Standard (RFS). The RFS mandated quantities of ethanol that blenders of gasoline are required to blend into the retail gasoline supply. These annual mandates are revised every year, but they were designed to steadily increase year after year until 2015 when the mandate reached 15 billion gallons per year. This figure came about because gasoline consumption in the United States was forecast to reach 150 billion gallons per year by 2015. So the RFS mandates were designed to reach the point where the entire retail gasoline supply would include 10% ethanol.</p>
<p>The EPA released <a href="https://www.epa.gov/renewable-fuel-standard-program/proposed-renewable-fuel-standards-2017-and-biomass-based-diesel">proposed rules</a> regarding RFS for volume requirements of biofuels for 2014, 2015, 2016, and 2017 on May 31, 2016.</p>
<table class="table">
<caption>Table 1: Renewable Fuel Mandated Volumes for 2014, 2015, 2016, and 2017</caption>
<colgroup>
<col style="width: 36%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">2014</th>
<th style="text-align: center;">2015</th>
<th style="text-align: center;">2016</th>
<th style="text-align: center;">2017</th>
<th style="text-align: center;">% Reduction in Greenhouse Gas Emissions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cellulosic biofuel (million gallons)</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">123</td>
<td style="text-align: center;">230</td>
<td style="text-align: center;">312</td>
<td style="text-align: center;">&gt; 60%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biomass-based diesel (billion gallons)</td>
<td style="text-align: center;">1.63</td>
<td style="text-align: center;">1.73</td>
<td style="text-align: center;">1.90</td>
<td style="text-align: center;">2.00</td>
<td style="text-align: center;">&gt; 50%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Advanced biofuel (billion gallons)</td>
<td style="text-align: center;">2.67</td>
<td style="text-align: center;">2.88</td>
<td style="text-align: center;">3.61</td>
<td style="text-align: center;">4.0</td>
<td style="text-align: center;">&gt; 50%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total Renewable fuel (billion gallons)</td>
<td style="text-align: center;">16.28</td>
<td style="text-align: center;">16.93</td>
<td style="text-align: center;">18.11</td>
<td style="text-align: center;">18.8</td>
<td style="text-align: center;">&gt; 20%</td>
</tr>
</tbody>
</table>
<p>: Table 1: Renewable Fuel Mandated Volumes for 2014, 2015, 2016, and 2017</p>
<p>Note: Units for all volumes are ethanol-equivalent, except for biomass-based diesel volumes which are expressed as physical gallons.|</p>
<p>Advanced biofuel is defined as fuel made from renewable sources that provides greater than 50% reduction in greenhouse gas emissions than the renewable fuel they replace. Cellulosic biofuel and biomass-based diesel are considered advanced biofuels, so the cellulosic and biomass-based diesel requirements comprise 2.13 billion gallons of the 3.61 billion gallon advanced biofuel requirement. This leaves 1.48 billion billion gallons in undifferentiated advanced biofuel in the mandate. This will most likely be fulfilled by importing sugarcane-based ethanol from Brazil, since the greenhouse gas emission reductions for sugarcane-based ethanol is accepted as an advanced biofuel and considered to have greater than 50% reduction in greenhouse gas emissions.</p>
<p>Since ethanol production is a significant user of corn, and has important price impacts, it is useful to calculate the implied corn usage under the RFS mandates. First, with an 18.11 billion gallon total renewable fuel requirement, and a 3.61 advanced biofuel requirement, that leaves <span class="math inline">\(18.11 - 3.61 = 14.5\)</span> billion gallons of the total renewable fuel requirement than can be met with conventional biofuel, like corn-based ethanol. Assuming an ethanol plant yields 2.8 gallons of ethanol per bushel of corn, that is an implied usage mandate of 5.17 billion bushels corn. This is spot on with the November 2015 WASDE’s estimate of Ethanol usage for the 2015/2016 marketing year of 5.175 billion bushels.</p>
<p>In the sections that follow the basic ethanol production process is presented. We discuss the by-product of ethanol production, distillers dried grains (DDGs), and its importance to the livestock industry. Then we will discuss some important price relationships involving ethanol, including the ethanol-RBOB gasoline price relationship, and the ethanol-corn-natural gas-DDGs price relationship.</p>
<section id="ethanol-production" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="ethanol-production"><span class="header-section-number">17.1</span> Ethanol Production</h2>
<p>Ethanol production<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> takes place at biorefineries <a href="http://www.ethanolrfa.org/resources/biorefinery-locations/">all across the country</a>, but production is concentrated in the corn belt. Ethanol plants take advantage of the plentiful supplies of corn and the relatively favorable basis in the corn belt. Some plants are located close to major livestock feeding operations. If you click the source link for the map below and zoom in to look more closely at Kansas you will see a few ethanol plants located in the vicinity of the cattle feedlots we explored in an earlier chapter.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/eth_locations.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure 1: Ethanol Plant Locations in the U.S.</figcaption>
</figure>
</div>
<p>Source: <a href="http://www.ethanolrfa.org/resources/biorefinery-locations/">Renewable Fuels Association</a></p>
<p>Corn-based ethanol can be produced via two methods. Dry grind, and wet grind.</p>
<section id="dry-grind-ethanol-production" class="level3" data-number="17.1.1">
<h3 data-number="17.1.1" class="anchored" data-anchor-id="dry-grind-ethanol-production"><span class="header-section-number">17.1.1</span> Dry Grind Ethanol Production</h3>
<p>In dry grind ethanol production, the entire kernel of corn is ground into a meal and mixed with water to create a slurry. Then enzymes are added to convert the starches in the slurry to simple sugar. Ammonia and yeast are added, and the yeast ferments the slurry and converts the slurry into ethanol and carbon dioxide. The ethanol is dehydrated to 200 proof and then a little gasoline is added to make the product undrinkable.</p>
<p>What is left over after the sugars have been converted to ethanol is called stillage. This product is dehydrated and sold as livestock feed called DDGs. The drying process usually is implemented with natural gas fueled furnaces, so natural gas is a significant input expense for dry grind ethanol plants. So dry-grind ethanol production involves two revenue streams, ethanol and Dd Gs. More on the economics of Dd Gs in the section that follows.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/640px-Ethanol_plant.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure 2: An Ethanol Plant</figcaption>
</figure>
</div>
<p>“<a href="https://commons.wikimedia.org/wiki/File:Ethanol_plant.jpg#/media/File:Ethanol_plant.jpg">Ethanol plant</a>”. Licensed under Public Domain via <a href="//commons.wikimedia.org/wiki/">Wikimedia Commons</a>.</p>
<p>Follow the link to a Google Maps satellite view of <a href="https://www.google.com/maps/place/Lincolnway+Energy+LLC/@42.0259566,-93.5094383,1084m/data=!3m1!1e3!4m2!3m1!1s0x0000000000000000:0xe75269d9c81692ab!6m1!1e1">Lincolnway Energy LLC, Ames, IA</a>. Note the location. The ethanol plant is located directly next to Key Cooperative, and both have access to a rail-head.</p>
</section>
<section id="wet-grind-ethanol-production" class="level3" data-number="17.1.2">
<h3 data-number="17.1.2" class="anchored" data-anchor-id="wet-grind-ethanol-production"><span class="header-section-number">17.1.2</span> Wet Grind Ethanol Production</h3>
<p>Unlike dry grind ethanol production, in the wet grind process whole corn kernels are steeped in a combination of sulfuric acid and water to separate the kernel into its components: pericarp (or skin), the endosperm (which contains the starch), and germ (which contains the oil). Pre-processing the corn in this way allows fermentation to be done on the starchy part alone, and corn oil and corn bran (from the pericarp) can be extracted separately. The wet-grind ethanol production involves three revenue streams, ethanol, corn oil, and corn bran.</p>
<p>Wet grind ethanol production is more costly than dry grind, so the majority of corn-based ethanol production capacity is of the dry grind type.</p>
</section>
</section>
<section id="distillers-grains" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="distillers-grains"><span class="header-section-number">17.2</span> Distiller’s Grains</h2>
<p>DDGs are a by product of the dry grind ethanol production process that is valuable as a livestock feed. DDGs have about 26% protein, 8% fat, and significant metabolizable energy (kcals), so it can be used to replace both energy (typically corn) and protein (soybean meal or other) requirements in feed rations.</p>
<p><a href="https://www.google.com/search?q=ddgs&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=0ahUKEwj4udmomr7JAhWF2B4KHailApcQ_AUICCgC&amp;biw=1920&amp;bih=1031#">Images of DDGs</a></p>
<section id="ddg-prices" class="level3" data-number="17.2.1">
<h3 data-number="17.2.1" class="anchored" data-anchor-id="ddg-prices"><span class="header-section-number">17.2.1</span> DDG Prices</h3>
<p>DDG prices tend to follow the trend of corn prices, although not perfectly because the two are not perfect substitutes. In figure 3, DDG and corn prices are compared using monthly U.S. average price received by farmers for corn (cents per bushel) and the average wholesale bulk price for Central IL ($/ton). We put corn prices in cents per bushel so the units are comparable on one axis.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/CornDDGPrices.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure 3: DDG and Corn Prices, Monthly Aug 2005 - 2021</figcaption>
</figure>
</div>
<p>It is also informative to look at the price ratio of DDG and corn prices. This is displayed in figure 4.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/DDGCORNRatio.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure 4: Ratio of DDG and Corn Prices, MonthlyAug 2005 - Oct 2015</figcaption>
</figure>
</div>
<p>The price ratio is fairly variable, but appears to follow a stationary and possibly mean reverting pattern. DDG prices seem to range from 30% to 50% of corn prices.</p>
</section>
</section>
<section id="ethanol-prices" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="ethanol-prices"><span class="header-section-number">17.3</span> Ethanol Prices</h2>
<p>Since ethanol is used as a liquid motor fuel, it makes sense that demand follows the same general trend that other energy products like crude oil and gasoline. This intuition is complicated, however, by the fact that ethanol is both a substitute and a compliment for gasoline. Blending ethanol at 10% with retail gasoline displaces, or substitutes for some quantity of gasoline. Also E85, 85% blend of gasoline, clearly substitutes for gasoline, although the size of the E85 market is small relative to the size of the retail gasoline market.</p>
<p>Ethanol is also a compliment with gasoline because it acts as an oxygenate. Oxygenates are added to retail gasoline to reduce carbon monoxide emissions and soot. By blending ethanol into retail gasoline blenders do not have to add other costly oxygenates derived from fossil fuels, such as MTBE (which is outlawed in California and New York among others) or <a href="https://en.wikipedia.org/wiki/Oxygenate">others</a>.</p>
</section>
<section id="ethanol-and-gas-prices" class="level2" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="ethanol-and-gas-prices"><span class="header-section-number">17.4</span> Ethanol and Gas Prices</h2>
<p>That said, it is difficult to anticipate whether Ethanol prices will exhibit a relationship consistent with a substitute or consistent with a complement good. In figure 5, ethanol and RBOB gasoline prices are graphed together for comparison.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/EthRBOB.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure 5: Iowa Ethanol Spot and Los Angelous Spot RBOB Gasoline Prices</figcaption>
</figure>
</div>
<p>It appears that ethanol and Los Angelos spot RBOB have a positive relationship consistent with substitute goods, but ethanol prices are usually discounted relative to gasoline prices. Geographical differences in transport costs likely explain part of this, but also, a gallon of ethanol has about 75% of the energy content of a gallon of gasoline. So gasoline with ethanol blended into it will yield fewer miles per gallon. This is particularly true for E85.</p>
</section>
<section id="ethanol-crush-spread" class="level2" data-number="17.5">
<h2 data-number="17.5" class="anchored" data-anchor-id="ethanol-crush-spread"><span class="header-section-number">17.5</span> Ethanol Crush Spread</h2>
<p>The price relationship between ethanol, its coproduct DDGs and its inputs, corn and natural gas, is also closely followed by the industry. Since we have recently ended a period of rapid expansion in the ethanol industry, ‘blending margins’ or the profitability of a typical ethanol plant were closely monitored to gauge how fast or slow we might expect future expansion. Although expansion has slowed, industry participants still follow the margin closely to determine the health of the industry and whether we can expect any idling of capacity or expansion.</p>
<p>Iowa State University Extension maintains an excellent spreadsheet model of ethanol economics. If you are involved in the commodity of ethanol industry, you will want to state up to date with the contents of the ISU model and what it says about economic conditions for ethanol production.</p>
<p><a href="https://www.extension.iastate.edu/agdm/articles/hof/HofJan08.html">Iowa State University Ethanol Plant Economic Model</a></p>
<p>Similar to the soybean crush, cattle crush, and crack spread, there exists futures contracts for ethanol, corn. This means that much of the ethanol production margins can be hedged or speculated on as we saw in the spreads of previous chapters. There are some limitations to this crush spread. The ethanol futures contract does not attract high trading volumes, which increases trading costs through higher Bid-Ask spreads. Also, there is no ddg futures contract, which means to hedge this revanue stream you have to use a cross hedge with with corn futures.</p>
<p>The ethanol producer’s profit is roughly,</p>
<ol type="1">
<li><span class="math inline">\(P_{eth}*q_{eth} + P_{DDG}*q_{DDG} - P_{corn}*q_{corn}\)</span></li>
</ol>
<p>A bushel of corn will yeild 2.8 gallons of ethanol and 17 lbs of ddgs, when processed into ethanol. Also, DDGs prices are quoted in $/tons, so we will need to convert that price to lbs (as we did for soybean meal). To calculate the Ethanol Crush, or the Gross Processing Margin (GPM), in terms of $/bushel of corn processed we need to to convert the prices of ethanol, and DDGs similarly to what we did for the soybean crush.</p>
<ol start="2" type="1">
<li><span class="math inline">\(P_{eth}*2.8 + P_{DDG}*17/2000 - P_{corn}\)</span></li>
</ol>
<p>Equation 2 gives the GPM per bushel of corn processed into ethanol. Dividing <span class="math inline">\(17/2000 = 0.0085\)</span> yields</p>
<ol start="3" type="1">
<li><span class="math inline">\(P_{eth}*2.8 + P_{DDG}*0.0085 - P_{corn}\)</span></li>
</ol>
<p><img src="assets/ECrushSpread.png" class="img-fluid" alt="Figure 6: Ethanol Crush Spread"> Note: Prices come from ISU Ethanol Profitability Model</p>
</section>
<section id="hedging-the-crush-spread" class="level2" data-number="17.6">
<h2 data-number="17.6" class="anchored" data-anchor-id="hedging-the-crush-spread"><span class="header-section-number">17.6</span> Hedging the Crush Spread</h2>
<p>Like soybean crushers, ethanol producers can use futures contracts to hedge their profitability. Ethanol producers buy corn and sell ethanol and DDGs, so the appropriate hedge trades would be to buy corn futures and sell (one month later) ethanol futures. An ethanol futures contract is for <span class="math inline">\(29,000\)</span> gallons of ethanol (the amount that will fill one typical train car).</p>
<p>Then two corn futures contracts produces just about one ethanol futures contract worth of ethanol, since</p>
<p><span class="math inline">\(10,000\)</span> bu corn <span class="math inline">\(= 10,000*2.8\)</span> gallons, or <span class="math inline">\(28,000\)</span> gallons of ethanol.</p>
<p>Therefore a 2-1 ratio of corn to ethanol contracts hedges the purchase of corn and the sale of ethanol, which will reduce the variability in GPM.</p>
<p>In this case, however, the sale of DDGs would remain unhedged. Since one bushel of corn weighs about <span class="math inline">\(56lbs\)</span> and one bushel of corn yeilds <span class="math inline">\(17lbs\)</span> of DDGs, by weight, the producer gets back <span class="math inline">\(17/56 = 0.30\)</span> in DDGs and the price of DDGs tracks the price of corn closely as we observed above. Intuitively, by hedging the purchase of corn and not the sale of DDGs, the ethanol producer would effectively be overhedged on the purchase of corn. With no viable futures contract for DDGs, the producer cannot directly solve this problem. Instead they can use a <strong>cross hedge</strong>.</p>
</section>
<section id="cross-hedging" class="level2" data-number="17.7">
<h2 data-number="17.7" class="anchored" data-anchor-id="cross-hedging"><span class="header-section-number">17.7</span> Cross Hedging</h2>
<p>When there is no futures contract for exact product or commodity that one needs to hedge, another futures contract whose price is highly correlated with the commodity you need to hedge can be used. In our case, we already observed above that the prices of DDGs and corn futures are highly correlated, so it may be beneficial to use corn futures to hedge the sale of DDGs.</p>
<section id="minimize-the-variance-of-cash-flow-with-optimal-hedge-ratio-for-ddgs-and-corn-futures" class="level3" data-number="17.7.1">
<h3 data-number="17.7.1" class="anchored" data-anchor-id="minimize-the-variance-of-cash-flow-with-optimal-hedge-ratio-for-ddgs-and-corn-futures"><span class="header-section-number">17.7.1</span> Minimize the Variance of Cash Flow with Optimal Hedge Ratio for DDGs and Corn Futures</h3>
<p>To develop the concept of a <em>cash flow variance minimizing</em> optimal hedge ratio, lets step back to the simpler example of a farmer hedging a crop of grain. We saw that the spot prices a farmer recieves is not exactly equal to the futures price for corn. Factors like transportation cost and local supply and demand conditions in the spot market make the basis, or the difference between spot and futures prices, variable. If this variability is too high, it may not be optimal to hedge with a 1-1 cash and futures position, even for the simple case of a farmer’s short hedge.</p>
<p>The farmer’s hedged cash flow</p>
<p><span class="math inline">\(CashFlow(t) = S(t) - b[F(t) - F(0)]\)</span><br>
<span class="math inline">\(CashFlow(t) = S(0) + S(t) - S(0) - b[F(t) - F(0)]\)</span><br>
<span class="math inline">\(CashFlow(t) = S(0) + \Delta S(t) - b\Delta F(t)\)</span></p>
<p>where <span class="math inline">\(S(t)\)</span> is the spot price at time <span class="math inline">\(t\)</span>, <span class="math inline">\(F(t)\)</span> is the futures price at time <span class="math inline">\(t\)</span>, and <span class="math inline">\(b\)</span> is the number of futures contracts used to hedge one ‘contracts’ worth of grain. Now examine the variance of this cash flow.</p>
<p><span class="math inline">\(Var[CashFlow(t)] = Var[S(0) + \Delta S(t) - b\Delta F(t)]\)</span><br>
<span class="math inline">\(Var[CashFlow(t)] = Var[\Delta S(t) - b\Delta F(t)]\)</span><br>
<span class="math inline">\(Var[CashFlow(t)] = Var[\Delta S(t)] + b^2Var[\Delta F(t)] - 2bCov[\Delta S(t),\Delta F(t)]\)</span></p>
<p>Now, naturally we want to minimize the variance of cash flow, so we can minimize this with respect to <span class="math inline">\(b\)</span> (take the derivative with respect to <span class="math inline">\(b\)</span>), and find the optimal number of futures contracts to use to hedge.</p>
<p>First order condition:</p>
<p><span class="math inline">\(0 = 2bVar[\Delta F(t)] - 2Cov[\Delta S(t),\Delta F(t)]\)</span></p>
<p>Solving for <span class="math inline">\(b\)</span>,</p>
<p><span class="math inline">\(b = \frac{Cov[\Delta S(t),\Delta F(t)]}{Var[\Delta F(t)]}\)</span></p>
<p>This, you may recognise, happens to be the coefficient estimate if we were to use linear regression to regress changes in spot price on changes in futures prices.</p>
<p><span class="math inline">\(\Delta S(t) = \beta_0 + b\Delta F(t) + \epsilon(t)\)</span></p>
<p>This means we can use historical prices to estimate the relationship between spot and futures prices, which yields the optimal hedge ratio for hedging the spot price with futures.</p>
</section>
</section>
<section id="exercises" class="level2" data-number="17.8">
<h2 data-number="17.8" class="anchored" data-anchor-id="exercises"><span class="header-section-number">17.8</span> Exercises</h2>
<p>The exercises for this chapter have you compute the optimal hedge ratio for using corn contracts to hedge DDG sales. Skills learned include:</p>
<ul>
<li><p>How to compute an optimal hedge ratio given price data.</p></li>
<li><p>How to run a regression in Excel.</p></li>
</ul>
<ol type="1">
<li>Compute the optimal hedge ratio for DDGs and corn futures.</li>
</ol>
<p>In a similar manner, we can determine the optimal hedge ratio for hedging DDG sales with corn futures by regressing changes in spot DDG prices on changes in corn futures prices. Open the .csv file provided.</p>
<p><a href="http://mindymallory.github.io/PriceAnalysis/Excel-files/Ethanol-Prices.csv">Cash Ethanol, DDG, and Corn Prices</a></p>
<p>Source: <a href="https://www.extension.iastate.edu/agdm/articles/hof/HofJan08.html">ISU’s ethanol plant profitability model</a></p>
<ol start="2" type="1">
<li>State the trades you should make to hedge one month’s production of ethanol for a plant that produces 100 millon gallons per year, with constant production throughout the year. Assuming we use the cross hedge determined in 1 to hedge the sale of DDGs.</li>
</ol>
</section>
<section id="readings" class="level2" data-number="17.9">
<h2 data-number="17.9" class="anchored" data-anchor-id="readings"><span class="header-section-number">17.9</span> Readings</h2>
<ol type="1">
<li><a href="http://www.cmegroup.com/trading/agricultural/files/AC-406_DDG_CornCrush_042010.pdf">Corn for Ethanol Crush Spread by CMEGroup</a></li>
</ol>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The information about ethanol production predominately comes from the <a href="https://en.wikipedia.org/wiki/Corn_ethanol">corn ethanol</a> Wikipedia page.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./16-TheSoybeanCrush.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">The Soybean Crush</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./18-BeefCattleMarkets.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Cattle Markets and the Livestock Crush</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>